### ISSUE TITLE
Typo in the definition of ithbsemsc1 

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#1]
This definition makes a reference to SC0 instead of SC1 on the line 312:
  (stor[SC0+SEMSC1]).po.(stor[REL&SEMSC1]) +
I believe it should be 
  (stor[SC1+SEMSC1]).po.(stor[REL&SEMSC1]) +
instead.

**Comment by jeffbolznv** [comment]
Hi @RobinMorisset,

Thanks for all the good issues. We discussed them in a TSG meeting this morning and I will fix/comment on the first five, and need a little more time to investigate the last two. We also have an update we'll be pushing out in the next few days which I would like to get merged before committing some of these fixes, just FYI.

**Comment by RobinMorisset** [comment]
Thanks for the quick answer.

I have one other issue which I am currently trying to wrap my head about:
- There is no direct translation of the "Scoped Memory Order Coherency" section from the spec to the formal model
- The acyclicity requirement in the consistent[X:Exec] predicate in the formal model has no direct equivalent in the spec (that I could find at least)
- These two don't seem equivalent to me: the acyclicity requirement looks significantly stronger, especially as hb is not transitive.
Do you want me to file an incomplete issue as soon as possible about this, or to first get an example where the two give different results, and some suggested fixes?

In any case, thank you for writing this very detailed memory model: I am nitpicking it, but I am very happy to see some rigorous memory model outside of academia.
