### ISSUE TITLE
"- (sthd & ref)" in the definition of datarace can be replaced by "- iden"

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#18]
This is not a bug in the specification, just a proposed small simplification.

Currently data races are defined by
dr = sloc & ((W -> W) + (W -> R) + (R -> W) - mutordatom - (sthd & sref) - rai[locord])

Consider a pair (a, b) which would be in dr if not for "- (sthd & sref)".
If a == b, it will also be prevented by -iden
If a != b, then either a <po b or b <po a, from the axiom "(sthd - iden) = rai[po]"
So a <hb b or b <hb a
Since (a, b) is in sthd&sloc&sref, either a <locord b or b <locord a
So (a, b) would be prevented by rai[locord].

**Comment by jeffbolznv** [comment]
Agreed, replacing with "- iden" also makes it more closely match the spec text that says "where X != Y".
