### ISSUE TITLE
Redundant use of storage[CBAR] in the last line of the definition of synchronizes-with

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#3]
This last line reads:
  ((stor[REL&F]) . (rc[po]) . (stor[CBAR]) . (scbarinst & inscope - iden) . (stor[CBAR]) . (rc[po]) . (stor[ACQ&F])))
Because scbarinst is guaranteed to be between CBARs (through the line 223: "is_equivalence[scbarinst, CBAR]"), I believe both (store[CBAR]) can be removed without changing the meaning of this line, turning it into:
  ((stor[REL&F]) . (rc[po]) . (scbarinst & inscope - iden) . (rc[po]) . (stor[ACQ&F])))

**Comment by jeffbolznv** [comment]
While this is redundant, IMO the CBARs help document the code, since you see all the critical instructions in the sequence. Thus I'm proposing a comment-only change.
