### ISSUE TITLE
Release sequences headed by relaxed stores

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#4]
Release sequences are used in 4 places in the spec, all 4 of them within the definition of synchronizes-with. In two of these places, release-sequences start from a release store, in the other two they start from an atomic write X with any memory semantics, with the comment that "If X is relaxed, it is still considered to head a hypothetical release sequence for this rule".

In the formal alloy model, release-sequences must start by a release write:
  rs = (stor[REL&A]) . *((imm[asmo]) . (stor[R&W]))
and in the two cases where they are supposed to be able to start from any atomic write, "rs" is replaced by "(stor[A&W]) . (rc[rs])".
The problem is that in the case where the store is not release, rc[rs] is equivalent to iden.
Is it a problem with the spec (in which case the sentence "If X is relaxed, it is still considered to head a hypothetical release sequence for this rule" is strongly misleading), or with the alloy formalization?

If it is a problem with the formalization, I would remove the requirement to start with a release store from rs:
rs = *((imm[asmo]) . (stor[R&W]))
and just replace rc[rs] by rs in the two places it occurs in synchronizes-with.
This should be enough as synchronizes-with already makes explicit the requirements on the head of the release sequence (being a release atomic, or being an atomic write of arbitrary semantics).

**Comment by jeffbolznv** [comment]
Agreed that this is an issue. I am a bit hesitant to make "rs" be something other than the release sequence, but maybe that can be solved by renaming it to something like "rssuffix". I'll put something together.

**Comment by jeffbolznv** [comment]
I ended up splitting hypothetical release sequence into its own relation. It made it easier not to break the releaseseq* tests that count how many release sequences there are.
