### ISSUE TITLE
Synchronizes-with appears to be missing an sref constraint

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#5]
For example the first element of the definition is:
  inscope & (
       // atomic->atomic
       ((stor[REL&A]) . rs . (rf & inscope) . (stor[ACQ&A])) +
The corresponding part of the spec says:
  If A and B are atomic operations, then A synchronizes-with B if and only if all of the following are true:
    A performs a release operation
    B performs an acquire operation
    A and B are mutually-ordered
    B reads a value written by A or by an operation in the release sequence headed by A
So the formalization appears to have replaced mutually-ordered by inscope. But mutually ordered does not only implies inscope, it also implies sref, and I do not where it is in the formal rule. The same thing is true of the other cases in the definition of synchronizes-with.

Am I missing something, or should this element be replaced by the following?
  inscope & (
      // atomic->atomic
      ((store[REL&A]) . rs . (rf & mutordatom) . (stor[ACQ&A])) +
Or alternatively:
  inscope & (
      // atomic->atomic
      ((store[REL&A]) . rs . (rf & inscope + sref) . (stor[ACQ&A])) +

**Comment by jeffbolznv** [comment]
"rf & mutordatom" (first option) is what we meant, I'll make a pull request.
