### ISSUE TITLE
Does scoped modification order relate reads?

### ISSUE THREAD

**Issue by RobinMorisset** [KhronosGroup/Vulkan-MemoryModel#7]
All I can find in the specification is:

> Scoped Modification Order
> For a given atomic operation A, all atomic operations that are mutually-ordered with A occur in an order known as A’s scoped modification order. A’s scoped modification order relates no other operations.

which hints that it includes reads.

But the formal model has a part saying:

> // A's scoped modification order:
> // - must be a strict partial order 
> // - must relate all mutually ordered atomic writes at the same location
> strict_partial_order[asmo]
> rai[asmo] = ((A&W) -> (A&W)) & mutordatom

From the name (modification order) and the details of the Scoped Modification Order Coherence section, I suspect the formal model is right here, and it is just an imprecision in the specification. Can you confirm this?

**Comment by jeffbolznv** [comment]
We discussed this today and propose to define scoped modification order to only include *modifications* (writes, RMW), as this is consistent with C++ and with "coherence order" in other models, as well as with its own name. So the Alloy model is correct and we'll update the spec text to match.

**Comment by jeffbolznv** [comment]
Proposed fix is at https://github.com/KhronosGroup/Vulkan-Docs/pull/906.
